[system]
lattice = "graphene"
formation_shape = "triangle" # rectangle | triangle
formation = "armchair"
size_x = 2
size_y = 2
# bond length (nm)
lattice_const = 0.142

[hamiltonian]
t1 = -2.8
t2 = -2.8
mu = 0.0
gamma = 0.01

[simulation]
use_strict_solver = false
dt = 0.2
t0 = 0.0
t_max = 500.0
a_tol = 1e-8
r_tol = 1e-10

[field]
intensity = 1e13
mode = "ddf"
phase = 0.0
omega = 0.2
t_shift = 200.0
sigma_gaus = 60.07
sigma_ddf = 0.01
ddf_omega = 0.1

[thermo]
T = 300

[features]
coulomb = true
