config = 'configs/SSH_config.toml'
config_hash_fnv1a64_hex = '7be3dc90a5f244a5'
date = '2026-02-01_16-32-33'
mode = 'time_impulse'

[field]
E0_au = 8.4401617508136876e-05
intensity_input = 10000000000000.0
omega_eV = 0.20000000000000001
sigma_ddf_fs = 0.01
sigma_gaus_fs = 60.0
t_shift_fs = 199.99999999999997

[hamiltonian]
gamma_eV = 0.01
mu_eV = 0.0
t1_eV = -2.7999999999999998
t2_eV = -2.7999999999999998

[simulation]
a_tol = 9.9999999999999995e-07
dt_fs = 0.0048377686530040008
r_tol = 1e-08
t0_fs = 0.0
t_max_fs = 500.00000000000006
use_strict_solver = true

[system]
N = 50
lattice_const_nm = 0.14199999999999999
two_dim = false

[thermo]
T_K = 300
