[system]
N = 50
lattice = "SSH"
lattice_const = 0.142
two_dim = false

[hamiltonian]
t1 = -2.8
t2 = -2.8
mu = 0.0
gamma = 0.05

[simulation]
dt = 0.2
t_end = 500
t0 = 0.0
a_tol = 1e-10
r_tol = 1e-12
use_strict_solver = false

[field]
intensity = 1e15
mode = "ddf"
omega = 0.2
t_shift = 200
sigma_gaus = 60.07
sigma_ddf = 0.01

[features]
spin = false
coulomb = false

[analysis]
omega_cut_off = 2.0

[thermo]
T = 300
